name: ci-job

on: 
  push:
    branches: [developer,release,main]

env:
  REGISTRY: nhat190899
  IMAGE_NAME_PREFIX: fsoft
  REPO_GITHUB_INFRA: nhat190899/gitops-sharing-infra
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment for branch
        run: echo "DOCKER_IMAGE=production" >> "$GITHUB_ENV"
      - run: echo ${{ env.DOCKER_IMAGE }}
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.20.0]
    steps:
      - uses: actions/checkout@v3
      - name: Use NodeJs ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm i
      - run: npm run build --if-present

  test-stage:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Running Tests
        uses: actions/checkout@v3
      - run: echo "runningggg"

  build-and-push-docker-image:
    name: Build docker image and push to repo
    runs-on: ubuntu-latest
    needs: ['build', 'test-stage']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup on Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image and push to Docker Hub and Git Container Registry
        uses: docker/build-push-action@v4
        with:
          context: ./
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_PREFIX }}-${{ env.ENVIRONMENT }}:${{ github.sha }}
          push: true
          platforms: linux/amd64,linux/arm64
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  update-manifest-stage:
    runs-on: ubuntu-latest
    needs: ['build-and-push-docker-image']
    steps: 
      - uses: actions/checkout@v3
        with: 
          repository: ${{ env.REPO_GITHUB_INFRA }}
          ref: 'main'
          token: ${{ secrets.G_TOKEN }}
      - name: setup-git-config
        run: |
          # git config --global user.email "nhat190899@gmail.com"
          # git config --global user.name "nhat190899"
          echo ${{ github.sha }}
          sed -i "s#${{ env.REGISTRY }}.*#${{ env.REGISTRY }}/${{ env.IMAGE_NAME_PREFIX }}-${{ env.ENVIRONMENT }}:${{ github.sha }}#g" value-${{ env.ENVIRONMENT }}.yaml
          git add -A 
          git commit -am "Update image for - ${{ github.sha }}"
      - run: echo ${{ github }}
      - run: git push origin main
          
